// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data.Database;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(MainDBContext))]
    partial class MainDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WebApplication1.Models.ProxmoxModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ProxmoxNetTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProxmoxToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProxmoxURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Proxmox");
                });

            modelBuilder.Entity("WebApplication1.Models.RancherModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RancherToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RancherURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rancher");
                });
#pragma warning restore 612, 618
        }
    }
}
